echo '$S_2$ $C_{0.4}$ & $S_2$ $C_{0.5}$ & $S_2$ $C_{0.6}$ & $S_2$ $C_{0.7}$ & $S_2$ $C_{0.8}$ & $S_3$ $C_{0.5}$ & $S_4$ $C_{0.5}$ & $S_5$ $C_{0.5}$ \\ '
cat smells-multiparameter.txt | grep s2c0_4 | awk '{s+=$2} END {printf "%d & ", s}'
cat smells-multiparameter.txt | grep s2c0_5 | awk '{s+=$2} END {printf "%d & ", s}'
cat smells-multiparameter.txt | grep s2c0_6 | awk '{s+=$2} END {printf "%d & ", s}'
cat smells-multiparameter.txt | grep s2c0_7 | awk '{s+=$2} END {printf "%d & ", s}'
cat smells-multiparameter.txt | grep s2c0_8 | awk '{s+=$2} END {printf "%d & ", s}'
cat smells-multiparameter.txt | grep s3c0_5 | awk '{s+=$2} END {printf "%d & ", s}'
cat smells-multiparameter.txt | grep s4c0_5 | awk '{s+=$2} END {printf "%d & ", s}'
cat smells-multiparameter.txt | grep s5c0_5 | awk '{s+=$2} END {printf "%d \\\\\n", s}'
cat candidates-multiparameter.txt | grep s2c0_4 | awk '{s+=$2} END {printf "%d & ", s}'
cat candidates-multiparameter.txt | grep s2c0_5 | awk '{s+=$2} END {printf "%d & ", s}'
cat candidates-multiparameter.txt | grep s2c0_6 | awk '{s+=$2} END {printf "%d & ", s}'
cat candidates-multiparameter.txt | grep s2c0_7 | awk '{s+=$2} END {printf "%d & ", s}'
cat candidates-multiparameter.txt | grep s2c0_8 | awk '{s+=$2} END {printf "%d & ", s}'
cat candidates-multiparameter.txt | grep s3c0_5 | awk '{s+=$2} END {printf "%d & ", s}'
cat candidates-multiparameter.txt | grep s4c0_5 | awk '{s+=$2} END {printf "%d & ", s}'
cat candidates-multiparameter.txt | grep s5c0_5 | awk '{s+=$2} END {printf "%d \\\\ ", s}'
