docker run -t --rm ccdc https://github.com/project-draco-hr/react-native.git 'androidTest|src_Test|_fixtures_|src_test' > react-native.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/elasticsearch.git 'src_test|test_src|test_framework' > elasticsearch.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/spring-framework.git 'src_test' > spring-framework.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/libgdx.git 'tests_' > libgdx.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/presto.git 'tests_src|src_test' > presto.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/platform_frameworks_base.git test > platform_frameworks_base.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/bazel.git 'src_test|_tests_|_test_|testing|_test\.' > bazel.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/deeplearning4j.git src_test > deeplearning4j.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/gradle.git 'src_test|tests_|test_' > gradle.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/druid.git src_test > druid.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/storm.git '_test_|_testing_' > storm.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/intellij-community.git '_test' > intellij-community.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/buck.git '_test|test_' > buck.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/openhab.git test > openhab.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/cassandra.git test > cassandra.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/processing.git test > processing.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/actor-platform.git test > actor-platform.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/atmosphere.git test > atmosphere.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/closure-compiler.git test > closure-compiler.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/orientdb.git 'test_|tests_' > orientdb.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/hadoop.git '_test_|-tests-' > hadoop.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/CoreNLP.git test_ > CoreNLP.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/pinpoint.git _test_ > pinpoint.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/h2o-2.git test > h2o-2.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/hibernate-orm.git 'test_|_testing_' > hibernate-orm.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/grails-core.git test > grails-core.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/android.git test > android.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/cas.git test > cas.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/hazelcast.git _test_ > hazelcast.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/bigbluebutton.git test > bigbluebutton.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/flink.git '_tests_|_test_|\-test\-' > flink.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/MinecraftForge.git test > MinecraftForge.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/groovy-core.git test > groovy-core.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/groovy.git test > groovy.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/jOOQ.git _test_ > jOOQ.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/h2o-3.git test > h2o-3.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/killbill.git _test_ > killbill.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/jmonkeyengine.git test > jmonkeyengine.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/FBReaderJ.git test > FBReaderJ.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/jitsi.git test > jitsi.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/hive.git test > hive.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/liquibase.git test > liquibase.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/Openfire.git _test_ > Openfire.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/Osmand.git test > Osmand.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/OpenTripPlanner.git _test_ > OpenTripPlanner.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/languagetool.git _test_ > languagetool.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/voltdb.git '_test|test_|tests_' > voltdb.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/BroadleafCommerce.git test > BroadleafCommerce.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/fabric8.git test > fabric8.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/MPS.git test > MPS.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/cgeo.git test > cgeo.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/drools.git test > drools.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/kotlin.git _test > kotlin.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/neo4j.git _test_ > neo4j.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/sonarqube.git '_test_|tests_|_test' > sonarqube.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/WordPress-Android.git _test_ > WordPress-Android.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/jetty.project.git test > jetty.project.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/dbeaver.git test > dbeaver.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/wildfly.git _test_ > wildfly.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/liferay-portal.git 'test_|_test|\-test' > liferay-portal.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/gwt.git test > gwt.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/Terasology.git test > Terasology.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/camel.git '_test_|_test|test_' > camel.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/hbase.git _test_ > hbase.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/vaadin.git test > vaadin.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/pentaho-kettle.git '_test|test_'> pentaho-kettle.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/Activiti.git _test_ > Activiti.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/basex.git test > basex.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/eucalyptus.git test > eucalyptus.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/restlet-framework-java.git test > restlet-framework-java.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/kaa.git _test_ > kaa.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/ambari.git _test > ambari.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/consulo.git _test > consulo.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/cloudstack.git test > cloudstack.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/android_packages_apps_Trebuchet.git test > android_packages_apps_Trebuchet.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/structr.git test > structr.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/mage.git _test_ > mage.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/mule.git '_test_|tests_' > mule.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/openmrs-core.git test > openmrs-core.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/jabref.git test > jabref.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/wicket.git test > wicket.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/geotools.git _test_ > geotools.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/i2p.i2p.git _test_ > i2p.i2p.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/cloudify.git test > cloudify.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/soapui.git test > soapui.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/CloudStack-archive.git test > CloudStack-archive.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/platform_packages_apps_settings.git test > platform_packages_apps_settings.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/keycloak.git _test > keycloak.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/usergrid.git _test > usergrid.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/Anki-Android.git test > Anki-Android.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/geoserver.git _test_ > geoserver.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/kylin.git test > kylin.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/jmeter.git '_test|test_' > jmeter.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/ignite.git '_test|test_'> ignite.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/optaplanner.git _test > optaplanner.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/intellij-plugins.git '_test|test_|_jstest'> intellij-plugins.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/legacy-jclouds.git '_test_|_speedtest' > legacy-jclouds.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/liferay-plugins.git _test > liferay-plugins.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/infinispan.git test > infinispan.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/lucene-solr.git _test > lucene-solr.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/ofbiz.git test > ofbiz.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/opencms-core.git test > opencms-core.mdg && \
docker run -t --rm ccdc https://github.com/project-draco-hr/isis.git src_test > isis.mdg
